Akhila Gadhiraju agadhira@stevens.edu

# bugs and issues

No

# resolved issue

I got an error in analysis.py beacause first I used user input which raised an error,late I used predefined list which resolved this.